#!/usr/bin/env bash

# Copyright (c) 2018 Verb Networks Pty Ltd <contact [at] verbnetworks.com>
#  - All rights reserved.
#
# Apache License v2.0
#  - http://www.apache.org/licenses/LICENSE-2.0

if [ -z ${1} ]; then
    echo ""
    echo "Usage: `basename ${0}` <terraform-tfstate> [custom-state]"
    echo ""
    echo " - push local salt-pillars and salt-states to host(s) via ssh-agent auth session."
    echo ""
    echo "    <terraform-tfstate> (required) - terraform.tfstate file, either local-file or aws-s3 location"
    echo "    <custom-state> (optional) - custom_state salt function to call"
    echo ""
    exit 1
fi

echo ''
echo `basename ${0}`
echo '==='

terraform_tfstate=${1}
custom_state=${2:-"state.highstate"}
ssh_port='22'
tfstate_tmp='/tmp/salt-push-tfstate-'$(head /dev/urandom | md5sum | head -c 8)'.tmp'

if [ `which jq | wc -l` -lt 1 ]; then
    echo 'ERROR: required binary "jq" not available on this system, please install it first.'
    exit 1
fi

if [ `which nc | wc -l` -lt 1 ]; then
    echo 'ERROR: required binary "nc" not available on this system, please install it first.'
    exit 1
fi

if [ `which rsync | wc -l` -lt 1 ]; then
    echo 'ERROR: required binary "rsync" not available on this system, please install it first.'
    exit 1
fi

if [ `echo "${terraform_tfstate}" | grep 's3://' | wc -l` -gt 0 ]; then
    aws s3 cp "${terraform_tfstate}" "${tfstate_tmp}"
    if [ ! -f ${tfstate_tmp} ]; then
        echo 'ERROR: tfstate not found at provided S3 location.'
        exit 1
    fi
    terraform_tfstate="${tfstate_tmp}"
fi

if [ ! -f ${terraform_tfstate} ]; then
    echo 'ERROR: unable to locate terraform.tfstate file.'
    exit 1
fi

local_minion_config_file=$(jq -r '.modules[].outputs.salt_local_minion_config_file.value' ${terraform_tfstate} | grep -v '^null' | head -n1)
local_minion_config_file=`realpath ${local_minion_config_file}`
echo 'local_minion_config_file: '${local_minion_config_file}

local_states_path=$(jq -r '.modules[].outputs.salt_local_state_tree.value' ${terraform_tfstate} | grep -v '^null' | head -n1 )
local_states_path=`realpath ${local_states_path}`
echo 'local_states_path: '${local_states_path}

local_pillars_path=$(jq -r '.modules[].outputs.salt_local_pillar_roots.value' ${terraform_tfstate} | grep -v '^null' | head -n1)
local_pillars_path=`realpath ${local_pillars_path}`
echo 'local_pillars_path: '${local_pillars_path}

remote_states_path=$(jq -r '.modules[].outputs.salt_remote_state_tree.value' ${terraform_tfstate} | grep -v '^null' | head -n1)
echo 'remote_states_path: '${remote_states_path}

remote_pillars_path=$(jq -r '.modules[].outputs.salt_remote_pillar_roots.value' ${terraform_tfstate} | grep -v '^null' | head -n1)
echo 'remote_pillars_path: '${remote_pillars_path}

if [ -z ${local_minion_config_file} ] || [ ! -e ${local_minion_config_file} ]; then
    echo 'ERROR: unable to find local_minion_config_file: '${local_minion_config_file}
    exit 1
fi

if [ ! -d ${local_states_path} ]; then
    echo 'ERROR: unable to locate local_states_path: '${local_states_path}
    exit 1
fi

if [ ! -d ${local_pillars_path} ]; then
    echo 'ERROR: unable to locate local_pillars_path: '${local_pillars_path}
    exit 1
fi

remote_address=$(jq -r '.modules[].resources[] | select(.type=="digitalocean_droplet") | .primary.attributes.ipv4_address' ${terraform_tfstate})
echo 'remote_address: '${remote_address}

nc -z -w5 ${remote_address} ${ssh_port}
if [ ${?} -gt 0 ]; then
    echo 'ERROR: unable to connect to '${remote_address}' on tcp:'${ssh_port}
    exit 1
fi
echo 'connect to '${remote_address}' on tcp:'${ssh_port}' - Okay!'

if [ ${local_minion_config_file} != '/dev/null' ]; then
    echo 'uploading local_minion_config_file and putting into place...'
    remote_temp_minion_config_file='/tmp/etc-salt-minion.'`date -u +%Y%m%dZ%H%M%S`
    scp "${local_minion_config_file}" ${remote_address}:${remote_temp_minion_config_file}
    ssh ${remote_address} "sudo mv ${remote_temp_minion_config_file} /etc/salt/minion; sudo chmod 0644 /etc/salt/minion; sudo chown root:root /etc/salt/minion"
fi

echo 'temp setting remote salt-config ownership to allow remote salt-config changes...'
ssh ${remote_address} "sudo chown -R \`whoami\`.\`whoami\` ${remote_states_path}; sudo chown -R \`whoami\`.\`whoami\` ${remote_pillars_path}"

rsync -ra --delete ${local_states_path}/ ${remote_address}:${remote_states_path}/
if [ ${?} -eq 0 ]; then
    echo 'rsyncd remote_states_path - Okay!'
else
    echo 'ERROR: problem rsyncing remote_states_path'
    exit 1
fi

rsync -ra --delete ${local_pillars_path}/ ${remote_address}:${remote_pillars_path}/
if [ ${?} -eq 0 ]; then
    echo 'rsyncd remote_pillars_path - Okay!'
else
    echo 'ERROR: problem rsyncing remote_pillars_path'
    exit 1
fi

echo 'setting remote salt-config ownership back to root...'
ssh ${remote_address} "sudo chown -R root.root ${remote_states_path}; sudo chown -R root.root ${remote_pillars_path}"

echo 'invoking salt-call over ssh...'
salt_call_command="sudo salt-call --local ${custom_state} --file-root=${remote_states_path} --pillar-root=${remote_pillars_path} --retcode-passthrough"
ssh ${remote_address} "${salt_call_command}"

if [ -f ${tfstate_tmp} ]; then
    rm -f "${tfstate_tmp}"
fi

echo ''
exit 0
